package io.github.yuroyami.kitessot

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class IoWorkerGenTest {

    @Test
    fun `emits the requested package`() {
        val src = generateIoWorkerSource("com.acme.app.generated")
        assertTrue(src.contains("package com.acme.app.generated"))
    }

    @Test
    fun `exposes the suspend offload entry point`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("suspend fun kiteSsotOffload(jobJs: String, payload: String): String"))
        assertTrue(src.contains("timeoutMillis: Long"))
        assertTrue(src.contains("KITE_SSOT_DEFAULT_TIMEOUT_MILLIS = 30_000L"))
    }

    @Test
    fun `wires the blob worker and coroutine bridge`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("URL.createObjectURL"))
        assertTrue(src.contains("new globalThis.Blob("))
        assertTrue(src.contains("import kotlinx.coroutines.suspendCancellableCoroutine"))
        assertTrue(src.contains("import kotlinx.coroutines.withTimeout"))
        assertTrue(src.contains("worker.terminate()"))
    }

    @Test
    fun `revokes the blob object URL to avoid a leak`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("finally { globalThis.URL.revokeObjectURL(u); }"), src)
    }

    @Test
    fun `carries the generated-do-not-edit banner`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("GENERATED by kitessot"))
        assertTrue(src.contains("DO NOT EDIT"))
    }

    @Test
    fun `does not leak a kotlin string-template dollar into the output`() {
        // The generated JS builds its bootstrap by concatenation, never `${...}`,
        // so the emitted file must not contain an unresolved template marker.
        val src = generateIoWorkerSource("kitessot.generated")
        assertFalse(src.contains("\${"))
    }

    // --- Protocol v2 (kept in sync with KiteCore's WebWorker) ---

    @Test
    fun `uses the protocol v2 request envelope`() {
        val src = generateIoWorkerSource("kitessot.generated")
        // The job reads its argument out of the envelope, not the raw message...
        assertTrue(src.contains("await job(e.data.payload)"))
        // ...and the Kotlin side posts { id, payload }, not a bare string.
        assertTrue(src.contains("message.id = KITE_SSOT_REQUEST_ID"))
        assertTrue(src.contains("message.payload = payload"))
        assertFalse(src.contains("worker.postMessage(payload)"))
    }

    @Test
    fun `reply echoes the correlation id and the handler matches it`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("id: id, ok: true"))
        assertTrue(src.contains("data.id == KITE_SSOT_REQUEST_ID"))
    }

    @Test
    fun `normalizes the worker result so an undefined job result does not hang`() {
        val src = generateIoWorkerSource("kitessot.generated")
        // Worker normalizes with '' + result...
        assertTrue(src.contains("result: '' + result"))
        // ...so the Kotlin side never calls .toString() on a maybe-undefined dynamic.
        assertFalse(src.contains("data.result.toString()"))
        assertFalse(src.contains("data.error.toString()"))
    }

    @Test
    fun `surfaces a useful worker error message instead of the bare event`() {
        val src = generateIoWorkerSource("kitessot.generated")
        // The old form stringified the ErrorEvent to "[object ErrorEvent]".
        assertTrue(src.contains("event.message"))
        assertTrue(src.contains("worker script failed to load or crashed"))
    }

    @Test
    fun `cancellation and timeout terminate the worker`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("withTimeout(timeoutMillis)"), src)
        assertTrue(src.contains("continuation.invokeOnCancellation { closeWorker() }"), src)
        assertTrue(src.contains("worker.onmessage = null"), src)
        assertTrue(src.contains("worker.onerror = null"), src)
        assertFalse(src.contains("CompletableDeferred"), src)
    }

    @Test
    fun `fails clearly outside browser worker environments`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("browserWorkerApisAvailable"), src)
        assertTrue(src.contains("Node.js-only and wasmJs runtimes are not supported"), src)
        assertTrue(src.contains("worker-src policy"), src)
    }

    @Test
    fun `documents raw code and dependency contracts in generated source`() {
        val src = generateIoWorkerSource("kitessot.generated")
        assertTrue(src.contains("jobJs is trusted executable JavaScript, not data"), src)
        assertTrue(src.contains("must declare kotlinx-coroutines-core"), src)
        assertTrue(src.contains("worker-src blob:"), src)
        assertTrue(src.contains("jobJs.isNotBlank()"), src)
    }
}
