[versions]
agp = "9.1.1"
kotlin = "2.3.20"
junit = "5.11.4"

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.11.4" }
