package io.github.yuroyami.kitessot

/**
 * Pure generator for the single-shot browser Web Worker helper emitted into a
 * selected Kotlin/JS target source set by [GenerateIoWorkerTask].
 *
 * This is deliberately a small browser helper, not a portable IO dispatcher. It
 * requires the consumer to declare `kotlinx-coroutines-core`, requires browser
 * `Worker`/`Blob`/object-URL APIs, and does not support a Node.js-only or wasmJs
 * target. The generated function accepts trusted raw JavaScript source; it must never
 * receive user-controlled text. A site's Content Security Policy must permit Blob
 * workers (normally `worker-src blob:`).
 *
 * The helper speaks the same protocol-v2 envelope as KiteCore's reusable
 * `WebWorker`: request `{ id, payload }`, reply `{ id, ok, result | error }`. It is
 * single-shot, bounds each call with a timeout, and terminates the worker on success,
 * failure, timeout, or coroutine cancellation.
 *
 * Kept pure (String in → String out) for focused generator tests.
 */
internal fun generateIoWorkerSource(packageName: String): String = """
/*
 * GENERATED by kitessot (io.github.yuroyami.kitessot) — DO NOT EDIT.
 * Regenerated for the selected browser target by its `generateKiteSsotIoWorker<Target>` task.
 *
 * Browser-only, single-shot Web Worker offload for Kotlin/JS.
 * The consumer must declare kotlinx-coroutines-core. This helper does not work in a Node.js-only
 * runtime or on wasmJs.
 *
 * SECURITY: jobJs is trusted executable JavaScript, not data. Never pass user,
 * network, database, or other untrusted input as jobJs. The worker has no access
 * to the Kotlin module; pass data through payload. Blob workers also require a
 * Content Security Policy that permits `worker-src blob:` (or its fallback).
 *
 * Example:
 *   val sum = kiteSsotOffload("(n) => { let s=0; for(let i=0;i<+n;i++) s+=i; return ''+s; }", "100000000")
 */
@file:Suppress("unused", "UNUSED_VARIABLE", "UNUSED_ANONYMOUS_PARAMETER")

package $packageName

import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withTimeout
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

private const val KITE_SSOT_REQUEST_ID = 1
private const val KITE_SSOT_DEFAULT_TIMEOUT_MILLIS = 30_000L

private fun browserWorkerApisAvailable(): Boolean =
    js("typeof globalThis !== 'undefined' && typeof globalThis.Worker === 'function' && typeof globalThis.Blob === 'function' && globalThis.URL != null && typeof globalThis.URL.createObjectURL === 'function' && typeof globalThis.URL.revokeObjectURL === 'function'")

// Revoke in finally so a CSP denial or Worker-construction failure cannot leak
// the object URL. `script` is trusted code by contract.
private fun makeBlobWorker(script: String): dynamic =
    js("(function(s){ var u = globalThis.URL.createObjectURL(new globalThis.Blob([s], { type: 'application/javascript' })); try { return new globalThis.Worker(u); } finally { globalThis.URL.revokeObjectURL(u); } })(script)")

// Protocol v2: request { id, payload } -> reply { id, ok, result | error }.
// jobJs is intentionally inserted as a function expression. It is code, not a
// serialization format, and callers must never derive it from untrusted input.
private fun workerBootstrap(jobJs: String): String =
    "self.onmessage = async function(e) {" +
    "  var id = e.data.id;" +
    "  try {" +
    "    var job = (" + jobJs + ");" +
    "    if (typeof job !== 'function') throw new TypeError('jobJs must be a function expression');" +
    "    var result = await job(e.data.payload);" +
    "    self.postMessage({ id: id, ok: true, result: '' + result });" +
    "  } catch (err) {" +
    "    self.postMessage({ id: id, ok: false, error: String((err && err.stack) || err) });" +
    "  }" +
    "};"

/**
 * Run trusted [jobJs] on a single-shot browser Web Worker with a 30-second
 * timeout. Cancellation and timeout terminate the worker before this call exits.
 *
 * This overload preserves the original two-argument API. Use the three-argument
 * overload when the job has a deliberate timeout budget.
 */
suspend fun kiteSsotOffload(jobJs: String, payload: String): String =
    kiteSsotOffload(jobJs, payload, KITE_SSOT_DEFAULT_TIMEOUT_MILLIS)

/**
 * Run trusted [jobJs] on a single-shot browser Web Worker, waiting no longer than
 * [timeoutMillis]. The worker is terminated on success, failure, cancellation, or
 * timeout. [jobJs] must be a self-contained function expression and must never be
 * built from untrusted input.
 *
 * @throws IllegalArgumentException if [jobJs] is blank or [timeoutMillis] is not positive
 * @throws UnsupportedOperationException outside a browser Worker environment
 * @throws kotlinx.coroutines.TimeoutCancellationException when the timeout expires
 */
suspend fun kiteSsotOffload(jobJs: String, payload: String, timeoutMillis: Long): String {
    require(jobJs.isNotBlank()) { "jobJs must be a non-blank trusted JavaScript function expression." }
    require(timeoutMillis > 0L) { "timeoutMillis must be greater than zero; got " + timeoutMillis }
    if (!browserWorkerApisAvailable()) {
        throw UnsupportedOperationException(
            "kiteSsotOffload requires browser Worker, Blob, and URL object APIs; " +
                "Node.js-only and wasmJs runtimes are not supported."
        )
    }

    return withTimeout(timeoutMillis) {
        suspendCancellableCoroutine { continuation ->
            val worker = try {
                makeBlobWorker(workerBootstrap(jobJs))
            } catch (cause: Throwable) {
                continuation.resumeWithException(
                    IllegalStateException(
                        "Unable to create the browser Web Worker. Check the site's worker-src policy.",
                        cause,
                    )
                )
                return@suspendCancellableCoroutine
            }

            var closed = false
            fun closeWorker() {
                if (!closed) {
                    closed = true
                    worker.onmessage = null
                    worker.onerror = null
                    runCatching { worker.terminate() }
                }
            }

            continuation.invokeOnCancellation { closeWorker() }
            if (!continuation.isActive) return@suspendCancellableCoroutine
            worker.onmessage = { event: dynamic ->
                val data = event.data
                if (data.id == KITE_SSOT_REQUEST_ID && continuation.isActive) {
                    closeWorker()
                    if (data.ok == true) {
                        continuation.resume("" + data.result)
                    } else {
                        continuation.resumeWithException(RuntimeException("" + data.error))
                    }
                }
                Unit
            }
            worker.onerror = { event: dynamic ->
                if (continuation.isActive) {
                    val detail: String =
                        if (event != null && event.message != null) "" + event.message
                        else "worker script failed to load or crashed"
                    closeWorker()
                    continuation.resumeWithException(
                        RuntimeException("kiteSsotOffload worker error: " + detail)
                    )
                }
                Unit
            }

            val message: dynamic = js("({})")
            message.id = KITE_SSOT_REQUEST_ID
            message.payload = payload
            try {
                worker.postMessage(message)
            } catch (cause: Throwable) {
                if (continuation.isActive) {
                    closeWorker()
                    continuation.resumeWithException(
                        IllegalStateException("Unable to post the Web Worker request.", cause)
                    )
                }
            }
        }
    }
}
""".trimStart()
