package io.github.yuroyami.kmpssot

/**
 * Pure generator for the runtime `KmpSsotBuildInfo` object emitted into the shared
 * module's `commonMain` by [GenerateBuildInfoTask]. Kept pure (values in → String
 * out) for unit testing, mirroring the plugin's other generators.
 *
 * Unset identity fields render as `""` (or `0` for the version code) so the object
 * always compiles; the app can treat empty as "not configured".
 */
internal fun generateBuildInfoSource(
    packageName: String,
    appName: String,
    versionName: String,
    versionCode: Int,
    androidApplicationId: String,
    iosBundleId: String,
    locales: List<String>,
): String {
    val localesLiteral = locales.joinToString(", ") { kotlinStringLiteral(it) }
    return """
        |/*
        | * GENERATED by kmp-ssot (io.github.yuroyami.kmpssot) — DO NOT EDIT.
        | * Regenerated on every build by the `generateKmpSsotBuildInfo` task.
        | */
        |package $packageName
        |
        |/** Single source of truth for app identity, readable at runtime. */
        |public object KmpSsotBuildInfo {
        |    public const val appName: String = ${kotlinStringLiteral(appName)}
        |    public const val versionName: String = ${kotlinStringLiteral(versionName)}
        |    public const val versionCode: Int = $versionCode
        |    public const val androidApplicationId: String = ${kotlinStringLiteral(androidApplicationId)}
        |    public const val iosBundleId: String = ${kotlinStringLiteral(iosBundleId)}
        |    public val locales: List<String> = listOf($localesLiteral)
        |}
        |""".trimMargin()
}

/** Render [s] as a safe Kotlin string literal (quotes, escapes `\`, `"`, `$`, control chars). */
internal fun kotlinStringLiteral(s: String): String {
    val sb = StringBuilder("\"")
    for (c in s) {
        when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '$' -> sb.append("\\$")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> sb.append(c)
        }
    }
    return sb.append("\"").toString()
}
