package io.github.yuroyami.kmpssot

/**
 * Pure generator for the runtime build-config object emitted into the shared
 * module's `commonMain` by [GenerateBuildConfigTask]. A buildKonfig-style typed
 * constants holder: the identity the plugin already computes, plus any user
 * `field(...)` declarations, readable from every KMP source set with no
 * `expect/actual`. Kept pure (values in → String out) for unit testing.
 *
 * Unset identity fields render as `""` / `0` so the object always compiles.
 * [customFields] are pre-rendered `NAME: TYPE = LITERAL` bodies (see
 * [buildConfigFieldLine]).
 */
internal fun generateBuildConfigSource(
    packageName: String,
    className: String,
    includeIdentity: Boolean,
    appName: String,
    versionName: String,
    versionCode: Int,
    androidApplicationId: String,
    iosBundleId: String,
    locales: List<String>,
    customFields: List<String>,
): String {
    val body = buildList {
        if (includeIdentity) {
            add("public const val appName: String = ${kotlinStringLiteral(appName)}")
            add("public const val versionName: String = ${kotlinStringLiteral(versionName)}")
            add("public const val versionCode: Int = $versionCode")
            add("public const val androidApplicationId: String = ${kotlinStringLiteral(androidApplicationId)}")
            add("public const val iosBundleId: String = ${kotlinStringLiteral(iosBundleId)}")
            add("public val locales: List<String> = listOf(${locales.joinToString(", ") { kotlinStringLiteral(it) }})")
        }
        customFields.forEach { add("public const val $it") }
    }
    val indented = body.joinToString("\n") { "    $it" }
    return """
        |/*
        | * GENERATED by kmp-ssot (io.github.yuroyami.kmpssot) — DO NOT EDIT.
        | * Regenerated on every build by the `generateKmpSsotBuildConfig` task.
        | */
        |package $packageName
        |
        |/** Single source of truth for app identity + custom fields, readable at runtime. */
        |public object $className {
        |$indented
        |}
        |""".trimMargin()
}

private val IDENTIFIER_RE = Regex("""[A-Za-z_][A-Za-z0-9_]*""")

/** A single dotless Kotlin identifier (field name, class name). */
internal fun isValidKotlinIdentifier(s: String): Boolean = IDENTIFIER_RE.matches(s)

/**
 * Render one build-config field body — the `NAME: TYPE = LITERAL` the generator
 * prefixes with `public const val`. [literal] is the already-rendered Kotlin RHS
 * (string values go through [kotlinStringLiteral]; numbers/booleans are verbatim).
 * Throws if [name] is not a valid identifier — the generated file would not compile.
 */
internal fun buildConfigFieldLine(type: String, name: String, literal: String): String {
    require(isValidKotlinIdentifier(name)) {
        "kmpSsot { buildConfig } field name \"$name\" is not a valid Kotlin identifier."
    }
    return "$name: $type = $literal"
}

/** Render [s] as a safe Kotlin string literal (quotes, escapes `\`, `"`, `$`, control chars). */
internal fun kotlinStringLiteral(s: String): String {
    val sb = StringBuilder("\"")
    for (c in s) {
        when (c) {
            '\\' -> sb.append("\\\\")
            '"' -> sb.append("\\\"")
            '$' -> sb.append("\\$")
            '\n' -> sb.append("\\n")
            '\r' -> sb.append("\\r")
            '\t' -> sb.append("\\t")
            else -> sb.append(c)
        }
    }
    return sb.append("\"").toString()
}
