package io.github.yuroyami.kmpssot

/**
 * Pure generator for the inline Web Worker offload helper emitted into a
 * consumer's `jsMain` source set by [GenerateIoWorkerTask].
 *
 * KMP has no `Dispatchers.IO` on the web target, so projects hand-roll a Worker
 * to push blocking/CPU-heavy work off the single JS main thread. This generates
 * the proven Blob-worker pattern once — no separate bundle or webpack config —
 * exposing a single `suspend fun kmpSsotOffload(jobJs, payload): String`.
 *
 * The generated file depends only on `kotlinx-coroutines-core` (already present
 * in any KMP project that needs offloading). It is the no-dependency quick start;
 * `io.github.yuroyami:kitecore` ships the richer typed `KiteWorker` + a unified
 * `ioDispatcher()` that this can install into.
 *
 * NOTE: the emitted Blob-worker bootstrap is an intentional duplicate of
 * KiteCore's `KiteWorker.bootstrap` (zero-dep codegen vs typed runtime lib) —
 * fix any worker-protocol bug in BOTH.
 *
 * Kept pure (String in → String out) for unit testing, mirroring the plugin's
 * other rewriters (`rewritePbxproj`, `sanitizeInfoPlist`, ...).
 */
internal fun generateIoWorkerSource(packageName: String): String = """
/*
 * GENERATED by kmp-ssot (io.github.yuroyami.kmpssot) — DO NOT EDIT.
 * Regenerated on every build by the `generateKmpSsotIoWorker` task.
 *
 * Inline Web Worker offload for Kotlin/JS. Spins up a Worker from a Blob URL and
 * runs a JS job function off the main thread, bridging the result back as a
 * suspend call. `jobJs` is a self-contained JS function expression
 * `(payload) => result` (sync or async). It runs in the Worker scope with NO
 * access to your Kotlin module — pass everything it needs through `payload`
 * (a String; serialize with JSON if you need structure).
 *
 * Example:
 *   val sum = kmpSsotOffload("(n) => { let s=0; for(let i=0;i<+n;i++) s+=i; return ''+s; }", "100000000")
 */
@file:Suppress("unused", "UNUSED_VARIABLE", "UNUSED_ANONYMOUS_PARAMETER")

package $packageName

import kotlinx.coroutines.CompletableDeferred

private fun makeBlobWorker(script: String): dynamic =
    js("new Worker(URL.createObjectURL(new Blob([script], { type: 'application/javascript' })))")

private fun workerBootstrap(jobJs: String): String =
    "self.onmessage = async function(e) {" +
    "  try {" +
    "    var job = (" + jobJs + ");" +
    "    var result = await job(e.data);" +
    "    self.postMessage({ ok: true, result: result });" +
    "  } catch (err) {" +
    "    self.postMessage({ ok: false, error: String((err && err.stack) || err) });" +
    "  }" +
    "};"

/**
 * Run [jobJs] (a JS function expression) on a Web Worker with [payload] as its
 * single argument, suspending until it returns. The worker is single-shot and
 * terminated once the result (or error) is delivered.
 */
suspend fun kmpSsotOffload(jobJs: String, payload: String): String {
    val worker = makeBlobWorker(workerBootstrap(jobJs))
    val deferred = CompletableDeferred<String>()
    worker.onmessage = { event: dynamic ->
        val data = event.data
        if (data.ok == true) {
            deferred.complete(data.result.toString())
        } else {
            deferred.completeExceptionally(RuntimeException(data.error.toString()))
        }
        worker.terminate()
        Unit
    }
    worker.onerror = { e: dynamic ->
        deferred.completeExceptionally(RuntimeException("kmpSsotOffload worker error: " + e))
        worker.terminate()
        Unit
    }
    worker.postMessage(payload)
    return deferred.await()
}
""".trimStart()
