package io.github.yuroyami.kmpssot

/**
 * Pure generator for the inline Web Worker offload helper emitted into a
 * consumer's `jsMain` source set by [GenerateIoWorkerTask].
 *
 * KMP has no `Dispatchers.IO` on the web target, so projects hand-roll a Worker
 * to push blocking/CPU-heavy work off the single JS main thread. This generates
 * the proven Blob-worker pattern once — no separate bundle or webpack config —
 * exposing a single `suspend fun kmpSsotOffload(jobJs, payload): String`.
 *
 * The generated file depends only on `kotlinx-coroutines-core` (already present
 * in any KMP project that needs offloading). It is the no-dependency quick start;
 * `io.github.yuroyami:kitecore` ships the richer typed `KiteWorker` + a unified
 * `ioDispatcher()` that this can install into.
 *
 * NOTE: the emitted Blob-worker bootstrap is an intentional duplicate of
 * KiteCore's `KiteWorker` bootstrap and speaks the same **protocol v2**:
 * request `{ id, payload }`, reply `{ id, ok, result | error }`, result
 * normalized with `'' + result` so `undefined` round-trips as `"undefined"`.
 * This is the zero-dep single-shot codegen; KiteCore ships the reusable typed
 * `KiteWorker` (js + wasmJs) on the same wire protocol. Fix any worker-protocol
 * bug in ALL copies (here + KiteCore's js and wasmJs). See KiteCore's
 * FABLE5_AUDIT.md §1 and §9.
 *
 * This helper is single-shot (one request, one reply, then `terminate()`), so
 * protocol v2's reusable-instance concerns — concurrent-call serialization and
 * `close()` failing an in-flight call — do not apply here; they live in
 * KiteCore's `KiteWorker`. The id envelope and result normalization still do,
 * and are mirrored below.
 *
 * Kept pure (String in → String out) for unit testing, mirroring the plugin's
 * other rewriters (`rewritePbxproj`, `sanitizeInfoPlist`, ...).
 */
internal fun generateIoWorkerSource(packageName: String): String = """
/*
 * GENERATED by kmp-ssot (io.github.yuroyami.kmpssot) — DO NOT EDIT.
 * Regenerated on every build by the `generateKmpSsotIoWorker` task.
 *
 * Inline Web Worker offload for Kotlin/JS. Spins up a Worker from a Blob URL and
 * runs a JS job function off the main thread, bridging the result back as a
 * suspend call. `jobJs` is a self-contained JS function expression
 * `(payload) => result` (sync or async). It runs in the Worker scope with NO
 * access to your Kotlin module — pass everything it needs through `payload`
 * (a String; serialize with JSON if you need structure).
 *
 * Example:
 *   val sum = kmpSsotOffload("(n) => { let s=0; for(let i=0;i<+n;i++) s+=i; return ''+s; }", "100000000")
 */
@file:Suppress("unused", "UNUSED_VARIABLE", "UNUSED_ANONYMOUS_PARAMETER")

package $packageName

import kotlinx.coroutines.CompletableDeferred

// This helper is single-shot: one worker per call, terminated on reply. The id
// is constant because there is only ever one request in flight per worker; it
// keeps the wire protocol identical to KiteCore's reusable KiteWorker.
private const val KMP_SSOT_REQUEST_ID = 1

private fun makeBlobWorker(script: String): dynamic =
    js("(function(){ var u = URL.createObjectURL(new Blob([script], { type: 'application/javascript' })); var w = new Worker(u); URL.revokeObjectURL(u); return w; })()")

// Protocol v2: request { id, payload } -> reply { id, ok, result | error }.
// The job reads its argument from e.data.payload, and the result is normalized
// with '' + so an undefined job result round-trips as the string "undefined"
// instead of throwing on the Kotlin side.
private fun workerBootstrap(jobJs: String): String =
    "self.onmessage = async function(e) {" +
    "  var id = e.data.id;" +
    "  try {" +
    "    var job = (" + jobJs + ");" +
    "    var result = await job(e.data.payload);" +
    "    self.postMessage({ id: id, ok: true, result: '' + result });" +
    "  } catch (err) {" +
    "    self.postMessage({ id: id, ok: false, error: String((err && err.stack) || err) });" +
    "  }" +
    "};"

/**
 * Run [jobJs] (a JS function expression) on a Web Worker with [payload] as its
 * single argument, suspending until it returns. The worker is single-shot and
 * terminated once the result (or error) is delivered.
 *
 * Safe to cancel: the caller's coroutine can be cancelled while the job runs;
 * the worker is discarded and its late reply ignored. A worker script that
 * fails to load (e.g. a syntax error in [jobJs]) rejects via onerror instead
 * of hanging, because the handlers are installed before the first postMessage.
 */
suspend fun kmpSsotOffload(jobJs: String, payload: String): String {
    val worker = makeBlobWorker(workerBootstrap(jobJs))
    val deferred = CompletableDeferred<String>()
    worker.onmessage = { event: dynamic ->
        val data = event.data
        if (data.id == KMP_SSOT_REQUEST_ID) {
            if (data.ok == true) {
                deferred.complete("" + data.result)
            } else {
                deferred.completeExceptionally(RuntimeException("" + data.error))
            }
            worker.terminate()
        }
        Unit
    }
    worker.onerror = { e: dynamic ->
        val detail: String =
            if (e != null && e.message != null) "" + e.message
            else "worker script failed to load or crashed"
        deferred.completeExceptionally(RuntimeException("kmpSsotOffload worker error: " + detail))
        worker.terminate()
        Unit
    }
    val message: dynamic = js("({})")
    message.id = KMP_SSOT_REQUEST_ID
    message.payload = payload
    worker.postMessage(message)
    return deferred.await()
}
""".trimStart()
