package io.github.yuroyami.kmpssot

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class IoWorkerGenTest {

    @Test
    fun `emits the requested package`() {
        val src = generateIoWorkerSource("com.acme.app.generated")
        assertTrue(src.contains("package com.acme.app.generated"))
    }

    @Test
    fun `exposes the suspend offload entry point`() {
        val src = generateIoWorkerSource("kmpssot.generated")
        assertTrue(src.contains("suspend fun kmpSsotOffload(jobJs: String, payload: String): String"))
    }

    @Test
    fun `wires the blob worker and coroutine bridge`() {
        val src = generateIoWorkerSource("kmpssot.generated")
        assertTrue(src.contains("URL.createObjectURL"))
        assertTrue(src.contains("new Blob("))
        assertTrue(src.contains("import kotlinx.coroutines.CompletableDeferred"))
        assertTrue(src.contains("worker.terminate()"))
    }

    @Test
    fun `carries the generated-do-not-edit banner`() {
        val src = generateIoWorkerSource("kmpssot.generated")
        assertTrue(src.contains("GENERATED by kmp-ssot"))
        assertTrue(src.contains("DO NOT EDIT"))
    }

    @Test
    fun `does not leak a kotlin string-template dollar into the output`() {
        // The generated JS builds its bootstrap by concatenation, never `${...}`,
        // so the emitted file must not contain an unresolved template marker.
        val src = generateIoWorkerSource("kmpssot.generated")
        assertFalse(src.contains("\${"))
    }
}
